# M8.5 Daily Ops Entrypoint
# Generated by stock_quant_v2 M8.5.
# This script does not trigger trading. It only runs ops checks and exports reports.

$ErrorActionPreference = "Stop"

Set-Location "D:\01_a_Project\10_python\01_Projects\Projet_stock_quant_v2\stock_quant_v2"

$env:M8_PORTFOLIO_ID = "1"
$env:M8_RISK_PROFILE_CODE = "paper_cn_a_risk3_strict_v1"
$env:M8_REPORT_OUTPUT_DIR = "artifacts/m8/daily_ops"
$env:M8_EXPORT_DAILY_REPORT = "true"
$env:M8_FAIL_ON_WARN = "false"

& "D:\01_a_Project\10_python\01_Projects\Projet_stock_quant_v2\stock_quant_v2\.venv\Scripts\python.exe" -m stock_quant_v2.scripts.m8_daily_ops_entrypoint

if ($LASTEXITCODE -ne 0) {
    Write-Host "M8.5 daily ops entrypoint failed with exit code $LASTEXITCODE"
    exit $LASTEXITCODE
}

Write-Host "M8.5 daily ops entrypoint completed."
exit 0
