from decimal import Decimal

DEFAULT_PAPER_ACCOUNT_CODE = "paper_cn_a_default"
DEFAULT_PAPER_PORTFOLIO_CODE = "paper_alpha_selection_v1_default"

DEFAULT_MARKET_CODE = "CN_A"
DEFAULT_BASE_CURRENCY = "CNY"
DEFAULT_INITIAL_CASH = Decimal("10000000.00000000")

DEFAULT_TARGET_COUNT = 30
DEFAULT_REBALANCE_FREQUENCY = "DAILY"
DEFAULT_PORTFOLIO_CONSTRUCTION_MODE = "EQUAL_WEIGHT_SELECTED"
DEFAULT_PRICE_FILL_RULE = "NEXT_OPEN"
DEFAULT_ORDER_TYPE = "MARKET"
DEFAULT_TIME_IN_FORCE = "DAY"

M6_METRIC_NAMESPACE = "m6_paper_trading"
M6_SERIES_NAMESPACE = "m6_paper_trading"