DEFAULT_MARKET_CODE = "CN_A"
DEFAULT_DAILY_BAR_PROVIDER = "baostock"
FALLBACK_DAILY_BAR_PROVIDER = "tushare"

SUPPORTED_EXCHANGES = ("SSE", "SZSE", "BSE")

DEFAULT_PRICE_ADJUST_TYPE = "RAW"

TRANSFORM_NORMALIZE_DAILY_BAR_V1 = "normalize_daily_bar_v1"
TRANSFORM_MERGE_DAILY_BAR_CORE_V1 = "merge_daily_bar_core_v1"
TRANSFORM_VERSION_M2_V1 = "m2.v1"